# Generated by Django 4.2.3 on 2023-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='type_user',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
